apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: k8s-multi-com-tls
spec:
  secretName: k8s-multi-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: rdvconsultoria.net
  dnsNames:
    - rdvconsultoria.net
    - www.rdvconsultoria.net
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - rdvconsultoria.net
          - www.rdvconsultoria.net
